services:
  web-chillameats:
    image: odoo:17.0
    user: root
    depends_on:
      - db-chillameats
    ports:
      - "8070:8069"
    volumes:
      - odoo-chillameats-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
  db-chillameats:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-chillameats-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo-chillameats-web-data:
  odoo-chillameats-db-data:
secrets:
  postgresql_password:
    file: ../odoo/odoo_pg_pass
